name: First Workflow
on: workflow_dispatch

env:
  TAG_NAME: my-image:v1

jobs:
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World $(date +%s)"
      - name: Goodbye
        run: echo "Goodbye $(date +%s)"
      - name: Tag Docker image
        run: |
          echo "$TAG_NAME-$(date +%s)"
